### ISSUE TITLE
Astral Additions Incompatible With Patchouli

### ISSUE THREAD

**Issue by OvercastAngel** [ethanicusss/AstralAdditions#5]
Title. When trying to boot up a game with both Patchouli and Astral Additions, the game crashes with an Exit Code: 1. I assume this is not intended behavior. Logs attached:
[latest.log](https://github.com/ethanicusss/AstralAdditions/files/12076001/latest.log)

**Comment by ethanicusss** [comment]
Thank you. This had been fixed with the most recent commit.
